name: pet_project
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.4
  image_picker: ^0.8.4+10
  json_serializable: ^6.1.4
  permission_handler: ^9.2.0
  video_player: ^2.2.13

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/video/dog-rendered.mp4
    - assets/images/bird.png
    - assets/images/cat.png
    - assets/images/dog.png
